# Generated by Django 5.2.7 on 2026-05-26 07:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.SmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('scope_category', models.CharField(blank=True, help_text="GHG Protocol sub-category, e.g. '3.6 Business travel'", max_length=50)),
                ('canonical_unit', models.CharField(help_text='Internal unit we normalize to', max_length=20)),
            ],
            options={
                'ordering': ['scope', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(default='*', help_text="Country code or '*' for global", max_length=10)),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Exclusive; null = currently active', null=True)),
                ('source_citation', models.CharField(max_length=500)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='emissions.activitytype')),
            ],
            options={
                'ordering': ['activity_type', 'region', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized to activity_type.canonical_unit. NULL when unit normalization failed (analyst must fix).', max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, default='', help_text='== activity_type.canonical_unit when known; empty string when activity_type is null', max_length=20)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='NULL when quantity could not be normalized or factor was missing. 0 would lie.', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('locked', 'Locked'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('flag_reasons', models.JSONField(blank=True, default=list, help_text='List of strings like ["unit_unknown"]')),
                ('source_payload', models.JSONField(help_text='Original row from the source system, untouched, for forensics')),
                ('source_row_identifier', models.CharField(help_text='Natural key from source (SAP doc#, bill ID, expense ID); used for dedup', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(blank=True, help_text="NULL when the source couldn't be classified (e.g., SAP material with no MaterialCodeMapping). Analyst must classify.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.activitytype')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null = ingested by system; non-null = manually added', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(blank=True, help_text='Frozen at compute time. Updating EmissionFactor does NOT recompute existing records. NULL when no matching factor existed at ingest time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.emissionfactor')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_locked', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='accounts.organization')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecordEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Mandatory on edits; optional on status transitions')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_edits', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edits', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['edited_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 (e.g., DE, US)', max_length=2)),
                ('facility_type', models.CharField(choices=[('plant', 'Plant'), ('office', 'Office'), ('fleet', 'Fleet'), ('other', 'Other')], default='plant', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.facility'),
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('sap', 'SAP (fuel/procurement)'), ('utility', 'Utility (electricity)'), ('travel', 'Corporate travel')], max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size_bytes', models.IntegerField()),
                ('file_sha256', models.CharField(help_text='Dedup: same org cannot upload same file twice', max_length=64)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_succeeded', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('row_count_flagged', models.IntegerField(default=0)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_batches', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='ingestion_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.ingestionbatch'),
        ),
        migrations.CreateModel(
            name='MaterialCodeMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_material_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.ForeignKey(blank=True, help_text='Null = seen but not yet classified by admin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_codes', to='emissions.activitytype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_code_mappings', to='accounts.organization')),
            ],
            options={
                'ordering': ['sap_material_code'],
            },
        ),
        migrations.CreateModel(
            name='PlantCodeMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_plant_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plant_codes', to='emissions.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_code_mappings', to='accounts.organization')),
            ],
            options={
                'ordering': ['sap_plant_code'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['activity_type', 'region', 'effective_from'], name='emissions_e_activit_933f68_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecordedit',
            index=models.Index(fields=['emission_record', 'edited_at'], name='ere_record_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_facility_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='ingestionbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'file_sha256'), name='unique_file_per_org'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status', '-period_end'], name='er_org_status_period_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'ingestion_batch'], name='er_org_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'facility', 'period_start', 'period_end'], name='er_org_facility_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialcodemapping',
            constraint=models.UniqueConstraint(fields=('organization', 'sap_material_code'), name='unique_material_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='plantcodemapping',
            constraint=models.UniqueConstraint(fields=('organization', 'sap_plant_code'), name='unique_plant_code_per_org'),
        ),
    ]
